/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: tamminen (https://sketchfab.com/tamminen)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/waterworld-7a3372278d124d4e8f90d7ae845ba082
title: Waterworld
*/
import { MeshStandardMaterial } from "three";
import React, { useEffect, useRef, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Model({ position, name, colori, size }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/waterworld.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (actions) {
      actions.Animation.play();
    }
  }, [actions]);

  return (
    <group ref={group} position={position} name={name} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Sphere_0">
                <mesh
                  name={name}
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials.material}
                  scale={size}
                />
              </group>
              <group name="Sphere001_1" scale={1.061}>
                <mesh
                  name={name}
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_6.geometry}
                  material={materials.material_1}
                  scale={size}
                />
              </group>
              <group name="Sphere002_2" scale={1.136}>
                <mesh
                  name={name}
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_8.geometry}
                  material={materials.material_2}
                  scale={size}
                />
              </group>
              <group name="Sphere003_3" scale={1.208}>
                <mesh
                  name={name}
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_10.geometry}
                  scale={size}
                  material={
                    new MeshStandardMaterial({
                      color: colori,
                      transparent: true,
                      opacity: 0.4,
                    })
                  }
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/waterworld.glb");
